spring:
  main:
    allow-circular-references: true
  application:
    name: hdiot_mq_demo
  rabbitmq:
    host: 10.201.1.166
    port: 5007
    username: admin
    password: 123qweasdzxc
    listener:
      queues: WS_YSCJ

server:
  port: 8093

